### ISSUE TITLE
Websocket not in wss

### ISSUE THREAD

**Issue by florent-n** [remotelabz/remotelabz#561]
When HTTPS is activated, the route send to the proxy is ws and it will be in wss

**Comment by florent-n** [comment]
The problem not seems to be about wss.
```bash
19:01:03.833 [ConfigProxy] info: Adding route /device/8e467a9f-9809-4f87-97a8-073613373eca -> ws://10.22.9.70:49887
19:01:03.834 [ConfigProxy] info: Route added /device/8e467a9f-9809-4f87-97a8-073613373eca -> ws://10.22.9.70:49887
19:01:03.835 [ConfigProxy] info: 201 POST /api/routes/device/8e467a9f-9809-4f87-97a8-073613373eca
19:01:04.744 [ConfigProxy] error: 503 GET /device/8e467a9f-9809-4f87-97a8-073613373eca connect ECONNREFUSED 10.22.9.70:49887
19:01:04.811 [ConfigProxy] error: Uncaught Exception: This socket has been ended by the other party
19:01:04.812 [ConfigProxy] error: Error: This socket has been ended by the other party
    at TLSSocket.writeAfterFIN [as write] (net.js:457:14)
    at /usr/lib/node_modules/configurable-http-proxy/lib/configproxy.js:491:28
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)```

**Comment by florent-n** [comment]
Not reproductible
