### ISSUE TITLE
proxy process restarts every 60 seconds

### ISSUE THREAD

**Issue by florent-n** [remotelabz/remotelabz#603]
In 2.2.3, we lost route to the VM because, every 60 second, the process restart.
```
PHP Fatal error:  Uncaught Symfony\Component\Process\Exception\ProcessTimedOutException: The process "'configurable-http-proxy' '--port' '8000' '--api-port' '8001'" exceeded the timeout of 60 seconds. in /home/florent/remotelabz/vendor/symfony/process/Process.php:1201
Mar 24 21:01:28 localhost, env[412211]: Stack trace:
Mar 24 21:01:28 localhost, env[412211]: #0 /home/florent/remotelabz/vendor/symfony/process/Process.php(413): Symfony\Component\Process\Process->checkTimeout()
Mar 24 21:01:28 localhost, env[412211]: #1 /home/florent/remotelabz/vendor/symfony/process/Process.php(234): Symfony\Component\Process\Process->wait()
Mar 24 21:01:28 localhost, env[412211]: #2 /home/florent/remotelabz/bin/remotelabz-proxy(48): Symfony\Component\Process\Process->run()
Mar 24 21:01:28 localhost, env[412211]: #3 {main}
Mar 24 21:01:28 localhost, env[412211]:   thrown in /home/florent/remotelabz/vendor/symfony/process/Process.php on line 1201
Mar 24 21:01:28 localhost, systemd[1]: remotelabz-proxy.service: Main process exited, code=exited, status=255/EXCEPTION
Mar 24 21:01:28 localhost, systemd[1]: remotelabz-proxy.service: Failed with result 'exit-code'.
Mar 24 21:01:29 localhost, systemd[1]: remotelabz-proxy.service: Scheduled restart job, restart counter is at 51.
Mar 24 21:01:29 localhost, systemd[1]: Stopped Remotelabz Proxy Service.
```

**Comment by florent-n** [comment]
Solved in 2.3.0 release
